name: Cypress Tests and Deploy Report

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SKVZ_CI repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run test

      - name: Generate report date
        id: report_date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Checkout mzilka.github.io repository
        uses: actions/checkout@v3
        with:
          repository: Z0lk01/mzilka.github.io
          token: ${{ secrets.REPORT_DEPLOY_TOKEN }}
          path: report-portal

      - name: Copy report to report-portal
        run: |
          mkdir -p report-portal/reports/SKVZ_CI/${{ steps.report_date.outputs.date }}
          cp -r public/* report-portal/reports/SKVZ_CI/${{ steps.report_date.outputs.date }}/
          rm -rf report-portal/reports/SKVZ_CI/latest
          cp -r report-portal/reports/SKVZ_CI/${{ steps.report_date.outputs.date }} report-portal/reports/SKVZ_CI/latest
      - name: Disable Jekyll build
        run: touch report-portal/.nojekyll

      - name: Commit and push report
        run: |
          cd report-portal
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy report for ${{ steps.report_date.outputs.date }}" --allow-empty
          git push
