version: 2.1  # verzia konfiguračného súboru

jobs:
  build:
    docker:  # definujeme obraz Dockeru
      - image: circleci/node:14  # použijeme obraz Node.js verzie 14

    
    parallelism: 3
    steps:  # kroky, ktoré sa majú vykonať v jobe
      - checkout  # stiahnutie kódu z repozitára
      - restore_cache:  # obnova cache pre npm balíčky
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # Ak sa nezmenil package-lock.json, použijeme uloženú cache

      - run: npm install  # inštalácia npm balíčkov

      - save_cache:  # uloženie cache pre npm balíčky
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Set file permissions
          command: chmod -R 755 cypress

      - run: npx test --record --key c64c4463-2120-476e-a8fd-f2da8db1b592  # spustenie testov s nahrávaním výsledkov do cloudu

workflows:
  version: 2  # verzia workflowu
  build_and_test:  # názov workflowu
    jobs:
      - build  # spustenie jobu 'build'  