version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          start-command: 'npm run start'
          cypress-command:
            'npx cypress run --parallel --record c64c4463-2120-476e-a8fd-f2da8db1b592 --group all tests'
          parallelism: 4