
/// <reference types="cypress" />
const { type } = require("os");
describe('Test TSS', () => {
        beforeEach(() => {
        cy
        .clearCookies()
        cy
        .clearLocalStorage()
        cy
        .visit("http://www.tssmonitoring.sk")
        cy.get('#user_login') 
        .type("mzilka:mza")
        cy.get('#user_pass')
        .type("alkoholik")
        cy.get("#wp-submit") .click()
        cy.wait(15000)
        cy.get(".confirm-modal-close") .click()
         
        });

it.only("Localization SK_1", () => {
        
        cy.get("#mainboard-filter-area > h1").should('contain', 'Dashboard')
        cy.get('#li-online-menu > [href="javascript:;"] > .title').should("be.visible") .click()
        cy.get('#gps_map_main').should("be.visible")
        .should("have.text", "Mapa")
        cy.get('#gps_units_online').should("be.visible")
        .should("have.text", "Dispečer")
        cy.get('#dashboard_online').should("be.visible")
        .should("have.text", "Grafické prehľady")
        cy.get('#gps_units_online_new').should("be.visible")
        .should("have.text", "Dispečer 2")
        cy.get('#unit-notifications').should("be.visible")
        .should("have.text", "Hlásenia")
        cy.get("#favorit-gps_map_main").should("not.be.visible")
        .should("have.class", "favorit empty")
        .click({force: true})
        cy.get("#favorit-gps_map_main").should("not.be.visible")
        .should("have.class", "favorit")
        .click({force: true})
        cy.get("#gps_map_main").click()
        cy.wait(2000)
        cy.get("#units-online-search").should("have.attr", "placeholder", "Hľadať vozidlo / osobu")
        .type("IL 942DE")
        cy.get('#company_name').should("be.visible")
        .should("have.text", "Firmy a strediská")
        cy.get('.all').should("be.visible")
        cy.get(".zap").should("be.visible")
        cy.get(".vyp").should("be.visible")
        cy.get(".not").should("be.visible")
        cy.get(".multi").should("be.visible")
        cy.get("#units-online-box").should("be.visible")
        cy.get('#li-online-menu > [href="javascript:;"] > .title').click()
        cy.get('#li-object > [href="javascript:;"]').click()
        cy.get('#users').should("be.visible")
        .should("have.text","UžívateliaVytváranie užívateľa")
        cy.get("#groups").should("be.visible")
        .should("have.text","Skupiny")
        cy.get("#usernew").should("be.visible")
        .should("have.text","Užívatelia newVytvoriť užívateľa")
        cy.get('#li-object > [href="javascript:;"]').click()
        cy.get('#li-rentcar > [href="javascript:;"]').should("be.visible")
        .should("have.text","Rezervačný systém").click()
        cy.get('#rent_cars_prepare_v2 > .title').should("be.visible")
        .should("have.text", "Autopožičovňa - priprave...")
        cy.get('#rent_cars_requests_for_me_v2 > .title').should("be.visible")
        .should("have.text", "Autopožičovňa - schvaľov...")
        cy.get('#busportals > .title').should("be.visible")
        .should("have.text", "Autobusy rezervácie")
        cy.get('#rent-cars-reports > .title').should("be.visible")
        .should("have.text", "Autopožičovňa reporty")
        cy.get('#rent_cars_my_requests_v2 > .title').should("be.visible")
        .should("have.text", "Autopožičovňa - moje žia...")
        cy.get('#rent_cars_v2').should("be.visible")
        .should("have.text", "Autopožičovňa")
        cy.get('#taxiportals').should("be.visible")
        .should("have.text", "Taxislužba")
        cy.get('#li-rentcar > [href="javascript:;"]').click()
        cy.get('#li-settings > [href="javascript:;"]').should("be.visible")
        .should("have.text", "Nastavenia").click()
        cy.get('#li-drivers > #drivers').should("be.visible")
        .should("have.text", "Vodiči")
        cy.get('#units').should("be.visible")
        .should("have.text", "Vozidlá")
        cy.get('#notifys').should("be.visible")
        .should("have.text", "UpozorneniaNotifikácie")
        cy.get('#centers').should("be.visible")
        .should("have.text", "Strediská")
        cy.get('#cost-centers').should("be.visible")
        .should("have.text", "Nákladové strediská")
        cy.get('#departments').should("be.visible")
        .should("have.text", "Oddelenia")
        cy.get('#li-settings > [href="javascript:;"]').click()
        cy.get('#li-poismenu > [href="javascript:;"]').should("be.visible")
        .should("have.text", "Body záujmu").click()
        cy.get('#pois').should("be.visible")
        .should("have.text", "Správa oblastí")
        cy.get('#poi_groups').should("be.visible")
        .should("have.text", "Správa kategórií oblastí")
        cy.get('#li-poismenu > [href="javascript:;"]').click()
        cy.get('#li-drivebooksmenu > [href="javascript:;"]').should("be.visible")
        .should("have.text", "Jazdy").click()
        cy.get('#drivebooks').should("be.visible")
        .should("have.text", "Správa jázd")
        cy.get('#drivetypes').should("be.visible")
        .should("have.text", "Účel jazdy")
        cy.get('#drive_conditions').should("be.visible")
        .should("have.text", "Pravidlá pre jazdy")
        cy.get('#drivebook_report_copy_0').should("be.visible")
        .should("have.text", "Kniha jázd")
        cy.get('#dailyreport_report_copy_0').should("be.visible")
        .should("have.text", "Denný prehľad jázd")
        cy.get('#monthlyreport_report_copy_0').should("be.visible")
        .should("have.text", "Mesačný/Súhrnný prehľad")
        cy.get('#drivetypesnew').should("be.visible")
        .should("have.text", "Účel jazdy")
        cy.get('#driveconditionsnew').should("be.visible")
        .should("have.text", "Pravidlá pre jazdy")
        cy.get('#motohours').should("be.visible")
        .should("have.text", "Motohodiny")
        cy.get('#fuel-analyses').should("be.visible")
        .should("have.text", "Sledovanie paliva")
        cy.get('#travel-allowance').should("be.visible")
        .should("have.text", "Pracovné cesty")
        cy.get('#newdrives').scrollIntoView({duration: 2000})
        .should("have.text", "Jazdy")
        cy.get('#drive-events').scrollIntoView()
        .should("have.text", "Udalosti jázd")
        cy.get('#consumptions').scrollIntoView()
        .should("have.text", "Správa spotrieb")
        cy.get('#routeplans').scrollIntoView()
        .should("have.text", "Plánovač trás")
        cy.get('#drivebooks_manuals').scrollIntoView()
        .should("have.text", "Evidencia jázd")
        cy.get('#li-drivebooksmenu > [href="javascript:;"]').click()
        cy.get('#li-drivestylesmenu > [href="javascript:;"]').should("be.visible")
        .should("have.text", "Štýl jazdy").click()
        cy.get('#drivestyles').should("be.visible")
        .should("have.text", "Štýl jazdy")
        cy.get('#drivestyle_report_copy_0').should("be.visible")
        .should("have.text", "Vyhodnotenie štýlu jazdy")
        cy.get('#li-drivestylesmenu > [href="javascript:;"]').click()
        cy.get('#li-reportsmenu > [href="javascript:;"]').should("be.visible")
        .should("have.text", "Reporty")
        cy.get('#li-fuelsmenu > [href="javascript:;"]').should("be.visible")
        .should("have.text", "Tankovania").click()
        cy.get('#addfuelcost').should("be.visible")
        .should("have.text", "Pridať tankovanie")
        cy.get('#fuelcards').should("be.visible")
        .should("have.text", "Tankovacie karty")
        cy.get('#fuel_cards_imports').should("be.visible")
        .should("have.text", "Import z tankovacích kariet")
        cy.get('#fuelreport_report_copy_0').should("be.visible")
        .should("have.text", "Prehľad tankovaní")
        cy.get('#li-fuelsmenu > [href="javascript:;"]').click()
        cy.get('#li-toolsmenu > [href="javascript:;"]').should("be.visible")
        .should("have.text", "Nástroje").click()
        cy.get('#corrections').should("be.visible")
        .should("have.text", "Korekcia tachometra")
        cy.get('#fuellevel_corrections').should("be.visible")
        .should("have.text", "Korekcia hladiny paliva")
        cy.get('#costs_report_copy_0').should("be.visible")
        .should("have.text", "Prehľad nákladov")
        cy.get('#costsnew').should("be.visible")
        .should("have.text", "Správa nákladov")
        cy.get('#service-books-v2').should("be.visible")
        .should("have.text", "Servisná kniha")
        cy.get('#li-toolsmenu > [href="javascript:;"]').click()
        cy.get('#li-tachographsmenu > [href="javascript:;"]').should("be.visible")
        .should("have.text", "Tachografy").click()
        cy.get('#aetr').should("be.visible")
        .should("have.text", "Aetrs")
        cy.get('#aetrsdispatchers').should("be.visible")
        .should("have.text", "Dispečer")
        cy.get('#aetrsnotifications').should("be.visible")
        .should("have.text", "Porušenia AETR")
        cy.get('#tachographs').should("be.visible")
        .should("have.text", "Stiahnuté súbory")
        cy.get('#aetrsdddviewers').should("be.visible")
        .should("have.text", "Prehliadač súborov")
        cy.get('#li-tachographsmenu > [href="javascript:;"]').click()
        cy.get('#li-workingsmenu > [href="javascript:;"]').should("be.visible")
        .should("have.text", "Práca").click()
        cy.get('#works').should("be.visible")
        .should("have.text", "Prehľad práce")
        cy.get('#li-workingsmenu > [href="javascript:;"]').click()
        cy.get('#li-vzv-menu > [href="javascript:;"]').should("be.visible")
        .should("have.text", "Vysokozdvižné vozíky").click()
        cy.get('#vzvusage').should("be.visible")
        .should("have.text", "Využiteľnosť VZV")
        cy.get('#li-vzv-menu > [href="javascript:;"]').click()
        cy.get('#li-planner > [href="javascript:;"]').should("be.visible")
        .should("have.text", "Plánovač").click()
        cy.get('#planners').should("be.visible")
        .should("have.text", "Plánovač")
        cy.get('#li-planner > [href="javascript:;"]').click()
        
});
it("Localization SK_2", () => {
        cy.get('#li-online-menu > [href="javascript:;"] > .title').should("be.visible") .click()
        cy.get('#gps_units_online_new').should("be.visible").click()
        cy.get('.gps_units_online_new_input_name_column > #gps_units_online_new_name_input')
        cy.get('#gps_units_online_new_panel').should("contains.text", "DISPEČER-ONLINE SPRÁVA")
        .should("contains.text", "Obnoviť")
        .should("contains.text", "záznamov na stranu")
        .should("contins.text", "Na celú obrazovku")
        .should("contains.text", "Vyp/Zap.stĺpce")
        .should("contains.text", "Jednotka")
        .should("contains.text", "Kontrola tachografu")
        .should("contains.text", "Poloha")
        .should("contains.text", "Rýchlosť")
        .should("contains.text", "Tachometer")
        .should("contains.text", "Stav paliva")
        .should("contains.text", "AdBlue")
        .should("contains.text", "Posledná aktualizácia")
        .should("contains.text", "Napätie")
        .should("contains.text", "Stredisko/Lokalita")




});


});