name: Cypress Tests and Deploy Report

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 5 * * *' # every day at 5:00 UTC

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SKVZ_CI repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress and generate report
        run: npm run report
        env:
          CYPRESS_username: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
        continue-on-error: true
        # This step will run the Cypress tests and generate the report.

      - name: Generate report date
        id: report_date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Checkout mzilka.github.io repository
        uses: actions/checkout@v3
        with:
          repository: Z0lk01/mzilka.github.io
          token: ${{ secrets.REPORT_DEPLOY_TOKEN }}
          path: report-portal

      - name: Copy report to report-portal
        run: |
          mkdir -p report-portal/reports/SKVZ_CI/${{ steps.report_date.outputs.date }}
          cp cypress/reports/index.html report-portal/reports/SKVZ_CI/${{ steps.report_date.outputs.date }}/index.html
          rm -rf report-portal/reports/SKVZ_CI/latest
          cp -r report-portal/reports/SKVZ_CI/${{ steps.report_date.outputs.date }} report-portal/reports/SKVZ_CI/latest

      - name: Disable Jekyll build
        run: touch report-portal/.nojekyll

      - name: Commit and push report
        run: |
          cd report-portal
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy report for ${{ steps.report_date.outputs.date }}" --allow-empty
          git push
